name: Publish Docker Image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

env:
  NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Environment
        run: |
          echo "NEXT_PUBLIC_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set Environment
        run: env | grep "^NEXT_" >> .env.production.local

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: NEXT_PUBLIC_VERSION
          target: runner
          tags: nghiepit/truestore-frontend:${{ env.NEXT_PUBLIC_VERSION }},nghiepit/truestore-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
